=== Angelramis/LMSGI/ud3_pack2_Angel_Segui/dtdex3.dtd
<!ELEMENT comanda (tractor+)>
<!ELEMENT tractor (component+)>
<!ATTLIST tractor n CDATA #REQUIRED>
<!ELEMENT component (nom_fabricant, data_entrega, fragil, pes, nombre_serie, kmmaxims?)>
<!ATTLIST component n CDATA #REQUIRED>
<!ELEMENT nom_fabricant (#PCDATA)>
<!ELEMENT data_entrega (dia?, mes, any)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT fragil (#PCDATA)>
<!ELEMENT pes (#PCDATA)>
<!ATTLIST pes unitat (quilos|grams) #REQUIRED>
<!ELEMENT nombre_serie (#PCDATA)>
<!ELEMENT kmmaxims (#PCDATA)>

=== Angelramis/LMSGI/ud3_pack2_Angel_Segui/ex2.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "dtdex3.dtd">

<comanda>
  <tractor n="1">
    <component n="1">
      <nom_fabricant>Rouis S.L</nom_fabricant>
      <data_entrega>
        <dia>5</dia>
        <mes>2</mes>
        <any>2024</any>
      </data_entrega>
      <fragil>Si</fragil>
      <pes unitat="quilos">30</pes>
      <nombre_serie>5784R</nombre_serie>
      <kmmaxims>60000</kmmaxims>
    </component>
    <component n="2">
      <nom_fabricant>Sistin S.L</nom_fabricant>
      <data_entrega>
        <dia>7</dia>
        <mes>3</mes>
        <any>2024</any>
      </data_entrega>
      <fragil>No</fragil>
      <pes unitat="grams">600</pes>
      <nombre_serie>9842S</nombre_serie>
    </component>
  </tractor>
</comanda>
