<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arxiu [
<!ELEMENT arxiu (operacions)>
<!ELEMENT operacions (venda | compra)+>
<!ELEMENT venda (titols_venuts, nom_titol, quantitat_llibres_venuts, lliurat, import)>
<!ELEMENT titols_venuts (#PCDATA)>
<!ELEMENT nom_titol (#PCDATA)>
<!ELEMENT quantitat_llibres_venuts (#PCDATA)>
<!ELEMENT lliurat (#PCDATA)>
<!ELEMENT import (#PCDATA)>
<!ATTLIST import moneda CDATA #REQUIRED>
<!ELEMENT compra (titols_comprats, nom_proveidor, data_compra)>
<!ELEMENT titols_comprats (#PCDATA)>
<!ELEMENT nom_proveidor (#PCDATA)>
<!ELEMENT data_compra (dia, mes, any)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>
]>

<arxiu>
  <operacions>
    <venda>
      <titols_venuts>2</titols_venuts>
        <nom_titol>La vida de Galicio</nom_titol>
      <quantitat_llibres_venuts>2</quantitat_llibres_venuts>
      <lliurat>Si</lliurat>
      <import moneda="euro">120.9</import>
    </venda>
    <compra>
      <titols_comprats>2</titols_comprats>
      <nom_proveidor>Llibres S.L</nom_proveidor>
      <data_compra>
        <dia>6</dia>
        <mes>2</mes>
        <any>2024</any>
      </data_compra>
    </compra>
  </operacions>
</arxiu>