=== Angelramis/LMSGI/ud3_pack6_Angel_Segui/empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="data_inici_contracte">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="salari">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>

  <xs:simpleType name="seu_treballant">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Madrid"/>
      <xs:enumeration value="Barcelona"/>
      <xs:enumeration value="ValÃ¨ncia"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="titol_academic">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="observacions">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="id">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="merit_demerit">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="cap_directe">
  <xs:simpleContent>
    <xs:extension base="xs:string">
      <xs:attribute name="id" type="xs:IDREF"/>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

  <xs:simpleType name="lloc_ocupat">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="dia">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>

  <xs:simpleType name="mes">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>

  <xs:simpleType name="any">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>

  <xs:complexType name="titols_academics">
    <xs:sequence>
      <xs:element name="titol_academic" type="titol_academic" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="merits_demerits">
    <xs:sequence>
      <xs:element name="merit" type="merit_demerit" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="demerit" type="merit_demerit" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="empleat">
    <xs:sequence>
      <xs:element name="nom_empleat" type="xs:string"/>
      <xs:element name="data_inici_contracte">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="dia" type="dia"/>
            <xs:element name="mes" type="mes"/>
            <xs:element name="any" type="any"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="lloc_actual" type="xs:string"/>
      <xs:element name="llocs_ocupats">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="lloc_ocupat" type="lloc_ocupat" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="cap_directe" type="xs:IDREF"/>
      <xs:element name="salari" type="salari"/>
      <xs:element name="titols_academics" type="titols_academics" minOccurs="0"/>
      <xs:element name="seu_treballant" type="seu_treballant"/>
      <xs:element name="observacions" type="observacions" minOccurs="0"/>
      <xs:element name="merits_demerits" type="merits_demerits" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="id"/>
  </xs:complexType>

  <xs:element name="empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleat" type="empleat" minOccurs="5" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Angelramis/LMSGI/ud3_pack6_Angel_Segui/ud3_ex6.4_Angel_Segui.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="empresa.xsd">

  <empleat id="1">
    <nom_empleat>Enrique Fernández</nom_empleat>
    <data_inici_contracte>
      <dia>05</dia>
      <mes>04</mes>
      <any>2020</any>
    </data_inici_contracte>
    <lloc_actual>Gerent</lloc_actual>
    <llocs_ocupats>
      <lloc_ocupat>Venedor telefònic</lloc_ocupat>
      <lloc_ocupat>Venedor físic</lloc_ocupat>
    </llocs_ocupats>
    <cap_directe id="2"/>
    <salari>40000</salari>
    <titols_acedemics>
      <titol_academic>Ingenieria ST</titol_academic>
      <titol_academic>Direccio Empreses</titol_academic>
    </titols_acedemics>
    <seu_treballant>Madrid</seu_treballant>
    <observacions>
      <merits>
        <merit>Paciencia</merit>
      </merits>
      <demerits>
        <demerit>Impulsivitat</demerit>
        <demerit>Falta de compromís</demerit>
      </demerits>
    </observacions>
  </empleat>

  <empleat id="2">
    <nom_empleat>Rodrigo Piñata</nom_empleat>
    <data_inici_contracte>
      <dia>12</dia>
      <mes>04</mes>
      <any>2021</any>
    </data_inici_contracte>
    <lloc_actual>Venedor telefònic</lloc_actual>
    <llocs_ocupats>
      <lloc_ocupat>Venedor telefònic</lloc_ocupat>
    </llocs_ocupats>
    <cap_directe id="3"/>
    <salari>40000</salari>
    <titols_acedemics>
      
    </titols_acedemics>
    <seu_treballant>València</seu_treballant>
  </empleat>

  <empleat id="3">
    <nom_empleat>Juan Fernández</nom_empleat>
    <data_inici_contracte>
      <dia>05</dia>
      <mes>04</mes>
      <any>2023</any>
    </data_inici_contracte>
    <lloc_actual>Director DF</lloc_actual>
    <llocs_ocupats>
      <lloc_ocupat>Director DFJ</lloc_ocupat>
    </llocs_ocupats>
    <cap_directe id="4"/>
    <salari>45000</salari>
    <titols_acedemics>
      <titol_academic>Tecnic Informatic</titol_academic>
    </titols_acedemics>
    <seu_treballant>Barcelona</seu_treballant>
    <observacions>
      <merits>
        <merit>Feiner</merit>
      </merits>
    </observacions>
  </empleat>

  <empleat id="4">
    <nom_empleat>Manolo Pinto</nom_empleat>
    <data_inici_contracte>
      <dia>02</dia>
      <mes>02</mes>
      <any>2020</any>
    </data_inici_contracte>
    <lloc_actual>Director Marketing</lloc_actual>
    <llocs_ocupats>
      <lloc_ocupat>Director Finanzes</lloc_ocupat>
      <lloc_ocupat>Cap de LDT</lloc_ocupat>
    </llocs_ocupats>
    <cap_directe id="6"/>
    <salari>50000</salari>
    <titols_acedemics>
      <titol_academic>Ingenieria SI</titol_academic>
      <titol_academic>Direccio Finanza</titol_academic>
      <titol_academic>Ingenieria PL</titol_academic>
    </titols_acedemics>
    <seu_treballant>Madrid</seu_treballant>
    <observacions>
      <demerits>
        <demerit>Ilògic</demerit>
      </demerits>
    </observacions>
  </empleat>

  <empleat id="5">
    <nom_empleat>Lucia Rodriquez</nom_empleat>
    <data_inici_contracte>
      <dia>01</dia>
      <mes>04</mes>
      <any>2023</any>
    </data_inici_contracte>
    <lloc_actual>Cap de projecte</lloc_actual>
    <llocs_ocupats>
      <lloc_ocupat>Cap de projecte</lloc_ocupat>
    </llocs_ocupats>
    <cap_directe id="8"/>
    <salari>10000</salari>
    <titols_acedemics>
      <titol_academic>Direccio Empreses</titol_academic>
    </titols_acedemics>
    <seu_treballant>València</seu_treballant>
    <observacions>
      
    </observacions>
  </empleat>

</empresa>
