=== Angelramis/LMSGI/ud3_pack3_Angel_Segui/ud3_ex3.3_Angel_Segui.dtd
<!ELEMENT entrega (lot+)>
<!ELEMENT lot (palet+)>
<!ATTLIST lot n CDATA #REQUIRED>
<!ELEMENT palet (nombre_caixes, contingut, pes_palet, forma_manipulacio)>
<!ATTLIST palet n CDATA #REQUIRED>
<!ELEMENT contingut (component+)>
<!ELEMENT component (nom_component, procedencia?, numero_serie, pes_component, unitat_pes?)>
<!ELEMENT procedencia (pais+)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT nom_component (#PCDATA)>
<!ELEMENT numero_serie (#PCDATA)>
<!ELEMENT pes_component (#PCDATA)>
<!ELEMENT unitat_pes (#PCDATA)>
<!ELEMENT nombre_caixes (#PCDATA)>
<!ELEMENT pes_palet (#PCDATA)>
<!ELEMENT forma_manipulacio (#PCDATA)>

=== Angelramis/LMSGI/ud3_pack3_Angel_Segui/ud3_ex3.3_Angel_Segui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entrega SYSTEM "ud3_ex3.3_Angel_Segui.dtd">
<entrega>
  <lot n="1">
    <palet n="1">
      <nombre_caixes>10</nombre_caixes>
      <contingut>
        <component>
          <nom_component>Processador</nom_component>
          <procedencia>
            <pais>Espanya</pais>
            <pais>Italia</pais>
          </procedencia>
          <numero_serie>5463TG</numero_serie>
          <pes_component>3</pes_component>
          <unitat_pes>quilos</unitat_pes>
        </component>
      </contingut>
      <pes_palet>15</pes_palet>
      <forma_manipulacio>Caixa</forma_manipulacio>
    </palet>
  </lot>
</entrega>
