=== Angelramis/LMSGI/ud3_pack3_Angel_Segui/ud3_ex3.2_Angel_Segui.dtd
<!ELEMENT llista_comandes (comanda*)>
<!ELEMENT comanda (numero_serie, quantitat, pes_quilos?)>
<!ATTLIST comanda n CDATA #REQUIRED>
<!ELEMENT numero_serie (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT pes_quilos (#PCDATA)>

=== Angelramis/LMSGI/ud3_pack3_Angel_Segui/ud3_ex3.2_Angel_Segui.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE llista_comandes SYSTEM "ud3_ex3.2_Angel_Segui.dtd">

<llista_comandes>
  <comanda n="1">
    <numero_serie>4564RT</numero_serie>
    <quantitat>2</quantitat>
    <pes_quilos>34</pes_quilos>
  </comanda>
  <comanda n="2">
    <numero_serie>2464RP</numero_serie>
    <quantitat>1</quantitat>
    <pes_quilos>34</pes_quilos>
  </comanda>
</llista_comandes>
