=== Angelramis/LMSGI/ud3_pack4_Angel_Segui/ud3_ex4.4_Angel_Segui.dtd
<!ELEMENT arxiu (llistat)>
<!ELEMENT llistat (futurs, divises, bons, lletres)>
<!ELEMENT futurs (futur+)>
<!ELEMENT divises (divisa+)>
<!ELEMENT bons (bo+)>
<!ELEMENT lletres (lletra+)>
<!ATTLIST futur n CDATA #REQUIRED preu CDATA #REQUIRED>
<!ELEMENT futur (procedencia, producte, mercat?)>
<!ATTLIST procedencia ubicacio CDATA #REQUIRED>
<!ELEMENT procedencia (#PCDATA)>
<!ELEMENT producte (#PCDATA)>
<!ELEMENT mercat (#PCDATA)>
<!ELEMENT divisa (producte_anterior, tipus_canvi+)>
<!ATTLIST divisa n CDATA #REQUIRED preu CDATA #REQUIRED estable CDATA #IMPLIED>
<!ATTLIST producte_anterior procedencia CDATA #REQUIRED>
<!ELEMENT tipus_canvi (#PCDATA)>
<!ATTLIST tipus_canvi n CDATA #REQUIRED>
<!ELEMENT bo (producte_anterior, pais_de_procedencia, valor_dessitjat, valor_minim, valor_maxim)>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT valor_dessitjat (#PCDATA)>
<!ELEMENT valor_minim (#PCDATA)>
<!ELEMENT valor_maxim (#PCDATA)>
<!ATTLIST bo n CDATA #REQUIRED preu CDATA #REQUIRED estable CDATA #IMPLIED>
<!ELEMENT lletra (producte_anterior, tipus_interes_pagable, pais_emissor)>
<!ELEMENT producte_anterior EMPTY>
<!ELEMENT tipus_interes_pagable (#PCDATA)>
<!ELEMENT pais_emissor (#PCDATA)>
<!ATTLIST lletra n CDATA #REQUIRED preu CDATA #REQUIRED>
<!ATTLIST producte_anterior ubicacio (Madrid | Nova_York | Frankfurt | Toquio) CDATA #REQUIRED>

=== Angelramis/LMSGI/ud3_pack4_Angel_Segui/ud3_ex4.4_Angel_Segui.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE arxiu SYSTEM "ud3_ex4.4_Angel_Segui.dtd">

<arxiu>
  <llistat>
    <futurs>
      <futur n="1" preu="100">
        <procedencia ubicacio="Espanya"></procedencia>
        <producte>MFJE</producte>
        <mercat>Espanya</mercat>
      </futur>
    </futurs>

    <divises>
      <divisa n="1" preu="12" estable="Si">Euro
        <producte_anterior ubicacio="Nova_York"></producte_anterior>
        <tipus_canvi n="1">Efectiu</tipus_canvi>
        <tipus_canvi n="2">Cr√©dit</tipus_canvi>
      </divisa>
    </divises>

    <bons>
      <bo n="1" preu="21" estable="No">
        <producte_anterior ubicacio="Toquio"></producte_anterior>
        <pais_de_procedencia>Espanya</pais_de_procedencia>
        <valor_dessitjat>100</valor_dessitjat>
        <valor_minim>10</valor_minim>
        <valor_maxim>200</valor_maxim>
      </bo>
    </bons>

    <lletres>
      <lletra n="1" preu="100">
        <producte_anterior ubicacio="Frankfurt"></producte_anterior>
        <tipus_interes_pagable>DFSF</tipus_interes_pagable>
        <pais_emissor>Espanya</pais_emissor>
      </lletra>
    </lletres>
  </llistat>
</arxiu>
