=== Angelramis/LMSGI/ud3_pack4_Angel_Segui/ud3_ex4.2_Angel_Segui.dtd
<!ELEMENT llistacursos (curs+)>
<!ELEMENT curs (alumne+)>
<!ELEMENT alumne (dni_alumne, nom_alumne, cognom_alumne, segon_cognom_alumne?, assignatures)>
<!ELEMENT dni_alumne (#PCDATA)>
<!ELEMENT nom_alumne (#PCDATA)>
<!ELEMENT cognom_alumne (#PCDATA)>
<!ELEMENT segon_cognom_alumne (#PCDATA)>
<!ELEMENT assignatures (assignatura+)>
<!ATTLIST assignatura n CDATA #REQUIRED codi CDATA #REQUIRED>
<!ELEMENT assignatura (nom_assignatura, professor)>
<!ELEMENT nom_assignatura (#PCDATA)>
<!ELEMENT professor (nrp_professor, nom_professor, cognom_professor, segon_cognom_professor?)>
<!ELEMENT nrp_professor (#PCDATA)>
<!ELEMENT nom_professor (#PCDATA)>
<!ELEMENT cognom_professor (#PCDATA)>
<!ELEMENT segon_cognom_professor (#PCDATA)>

<!ATTLIST curs n CDATA #REQUIRED>
<!ATTLIST alumne n CDATA #REQUIRED>

=== Angelramis/LMSGI/ud3_pack4_Angel_Segui/ud3_ex4.2_Angel_Segui.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE llistacursos SYSTEM "ud3_ex4.2_Angel_segui.dtd">

<llistacursos>
  <curs n="1">
    <alumne n="1">
      <dni_alumne>41434553J</dni_alumne>
      <nom_alumne>Galicio</nom_alumne>
      <cognom_alumne>Díaz</cognom_alumne>
      <segon_cognom_alumne>Pérez</segon_cognom_alumne>
      <assignatures>
          <assignatura n="1" codi="425F">
            <nom_assignatura>Valors étics</nom_assignatura>
            <professor>
              <nrp_professor>2432532562</nrp_professor>
              <nom_professor>Juan</nom_professor>
              <cognom_professor>Pérez</cognom_professor>
              <segon_cognom_professor>Castillos</segon_cognom_professor>
            </professor>
        </assignatura>
      </assignatures>
    </alumne>
  </curs>
</llistacursos>
