=== Angelramis/LMSGI/ud3_pack4_Angel_Segui/ud3_ex4.3_Angel_Segui.dtd
<!ELEMENT arrel (llibres*, cuaderns*, llapisos*)>
<!ELEMENT llibres (llibre+)>
<!ELEMENT llibre (#PCDATA)>
<!ATTLIST llibre titol CDATA #REQUIRED>
<!ELEMENT cuaderns (cuadern+)>
<!ATTLIST cuadern num_fulles CDATA #IMPLIED>
<!ELEMENT cuadern (#PCDATA)>
<!ELEMENT llapisos (llapis+)>
<!ATTLIST llapis numero CDATA #REQUIRED>
<!ELEMENT llapis (#PCDATA)>

=== Angelramis/LMSGI/ud3_pack4_Angel_Segui/ud3_ex4.3_Angel_Segui.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE arrel SYSTEM "ud3_ex4.3_Angel_Segui.dtd">

<arrel>
  <llibres>
    <llibre titol="El camino de la vida"></llibre>
    <llibre titol="El camino de la vida"></llibre>
    <llibre titol="El camino del oeste"></llibre>
    <llibre titol="La vida acÃºstica"></llibre>
  </llibres>
  <cuaderns>
    <cuadern num_fulles="130"></cuadern>
    <cuadern num_fulles="100"></cuadern>
  </cuaderns>
  <llapisos>
    <llapis numero="24"></llapis>
    <llapis numero="4"></llapis>
  </llapisos>
</arrel>
